version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: install-yarn
          command: 'sudo npm install -g yarn'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-yarn-wee
          command: yarn
      - run:
          name: install-flow-typed-wee
          command: yarn run flow-typed install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
