version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
          CYPRESS_baseUrl: http://localhost:5000
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn and Cypress Cache
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn and Cypress Cache
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - run:
          name: Install flow-typed
          command: yarn run flow-typed install
      - run:
          name: Change git config to support UTF8 filename
          command: git config --global core.quotepath false
      - run:
          name: Linting and unit test
          command: yarn test
      - run:
          name: End to end test
          command: |
            yarn run compile
            yarn run serve:embauche &
            yarn run cypress run --record --key 21660df5-36a5-4c49-b23d-801799b0c759
