

# InFrance PRODUCTION settings

[[redirects]]
from = "https://www.mycompanyinfrance.fr/*"
to = "https://mycompanyinfrance.fr/:splat"
status = 301

[[redirects]]
from = "https://mycompanyinfrance.fr/robots.txt"
to = "/robots.infrance.txt"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr/sitemap.txt"
to = "/sitemap.infrance.en.txt"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr"
to = "/prerender/infrance/index.html"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr/social-security"
to = "/prerender/infrance/social-security/index.html"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr/*"
to = "/infrance.html"
status = 200

# Mon-entreprise.fr PRODUCTION settings

[[redirects]]
from = "https://mon-entreprise.fr/stats"
to = "https://branched-trunk.glitch.me/"
status = 200

[[redirects]]
from = "https://mon-entreprise.fr/robots.txt"
to = "/robots.infrance.txt"
status = 200

[[redirects]]
from = "https://mon-entreprise.fr/sitemap.txt"
to = "/sitemap.infrance.fr.txt"
status = 200

[[redirects]]
from = "https://mon-entreprise.fr"
to = "/prerender/mon-entreprise/index.html"
status = 200

[[redirects]]
from = "https://mon-entreprise.fr/*"
to = "/mon-entreprise.html"
status = 200


# Embauche PRODUCTION settings

[[redirects]]
from = "https://embauche.beta.gouv.fr/"
to = "https://mon-entreprise.fr/sécurité-sociale/salarié"
status = 301

[[redirects]]
from = "https://embauche.beta.gouv.fr/documentation/*"
to = "https://mon-entreprise.fr/documentation/:splat"
status = 301

[[redirects]]
from = "https://embauche.beta.gouv.fr/"
to = "https://mon-entreprise.fr/sécurité-sociale/salarié"
status = 301

# Old iframe adresse
[[redirects]]
from = "https://embauche.beta.gouv.fr/modules/v2/*"
to = "/:splat"

# When in iframe, we don't prerender the page
[[redirects]]
from = "https://embauche.beta.gouv.fr/"
query = {iframe=":iframe", s=":e", couleur=":couleur", integratorUrl=":integratorUrl", lang=":lang"}
to = "/embauche.html?iframe=:iframe&s=:e&couleur=:couleur&integratorUrl=:integratorUrl&lang=:lang"
status = 200


# Redirect to mycompanyinfrance in staging and development settings
[[redirects]]
from = "/"
query = {s = "m"}
to = "/prerender/infrance/index.html"
status = 200


[[redirects]]
from = "/*"
query = {s = "m"}
to = "/infrance.html"
status = 200

# Redirect to mon-entreprise in staging and development settings
[[redirects]]
from = "/"
to = "/prerender/mon-entreprise/index.html"
status = 200
[[redirects]]
from = "/*"
to = "/mon-entreprise.html"
status = 200


[context.deploy-preview.environment]
  EN_SITE = "${path}?s=m"
  FR_SITE = "${path}"

[context.production.environment]
  EN_SITE = "https://mycompanyinfrance.fr${path}"
  FR_SITE = "https://mon-entreprise.fr${path}"
  MASTER = 'true'

[context."demo"]
  EN_SITE = "https://demo.mon-entreprise.fr${path}?s=m"
  FR_SITE = "https://demo.mon-entreprise.fr${path}"
