[[redirects]]
from = "https://infrance.org/*"
to = "/infrance.html"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr/*"
to = "/infrance.html"
status = 200

[[redirects]]
from = "https://embauche.beta.gouv.fr/*"
to = "/embauche.html"
status = 200

[[redirects]]
from = "/*"
query = {site = "embauche"}
to = "/embauche.html"
status = 200

[[redirects]]
from = "/*"
to = "/infrance.html"
status = 200
