[[redirects]]
from = "https://embauche.beta.gouv.fr/stats"
to = "https://remarkable-ogre.glitch.me/"
status = 200

[[redirects]]
from = "https://infrance.org/*"
to = "/infrance.html"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr/robots.txt"
to = "/robots.infrance.txt"
status = 200

[[redirects]]
from = "https://mycompanyinfrance.fr/*"
to = "/infrance.html"
status = 200


[[redirects]]
from = "https://embauche.beta.gouv.fr/modules/v2/*"
to = "/:splat"

[[redirects]]
from = "https://embauche.beta.gouv.fr/robots.txt"
to = "/robots.embauche.txt"
status = 200

[[redirects]]
from = "https://embauche.beta.gouv.fr/*"
to = "/embauche.html"
status = 200


[[redirects]]
from = "/*"
query = {s = "e"}
to = "/embauche.html"
status = 200

[[redirects]]
from = "/*"
to = "/infrance.html"
status = 200
